// ── Mock Marketplace Data ─────────────────────────────────────────────────
// PHASE 2 UPGRADE POINT: Replace with API calls to your database

export interface MarketplaceTemplate {
  id: string;
  title: string;
  description: string;
  category: string;
  type: string;
  price: number;
  seller: {
    id: string;
    name: string;
    avatar: string;
    rating: number;
    totalSales: number;
  };
  rating: number;
  reviewCount: number;
  downloadCount: number;
  previewColor: string;
  tags: string[];
  featured: boolean;
  createdAt: string;
  reviews: Review[];
}

export interface Review {
  id: string;
  author: string;
  avatar: string;
  rating: number;
  comment: string;
  date: string;
}

const SELLERS = [
  { id: 's1', name: 'Alexandra Chen', avatar: 'AC', rating: 4.9, totalSales: 1240 },
  { id: 's2', name: 'Marcus Williams', avatar: 'MW', rating: 4.8, totalSales: 876 },
  { id: 's3', name: 'Priya Patel', avatar: 'PP', rating: 5.0, totalSales: 2100 },
  { id: 's4', name: 'Jordan Lee', avatar: 'JL', rating: 4.7, totalSales: 654 },
  { id: 's5', name: 'Sofia Rodriguez', avatar: 'SR', rating: 4.9, totalSales: 1560 },
  { id: 's6', name: 'David Kim', avatar: 'DK', rating: 4.8, totalSales: 932 },
  { id: 's7', name: 'Amara Osei', avatar: 'AO', rating: 4.9, totalSales: 743 },
  { id: 's8', name: 'Ryan Thompson', avatar: 'RT', rating: 4.6, totalSales: 421 },
];

const SAMPLE_REVIEWS: Review[] = [
  { id: 'r1', author: 'Jessica M.', avatar: 'JM', rating: 5, comment: 'Absolutely stunning template! Saved me hours of work and the output looked incredibly professional.', date: '2 days ago' },
  { id: 'r2', author: 'Tom K.', avatar: 'TK', rating: 5, comment: 'Used this for my startup pitch deck. Investors loved the structure. Worth every penny!', date: '1 week ago' },
  { id: 'r3', author: 'Sarah L.', avatar: 'SL', rating: 4, comment: 'Great template, very well organized. Minor formatting tweaks needed but overall excellent.', date: '2 weeks ago' },
  { id: 'r4', author: 'Alex P.', avatar: 'AP', rating: 5, comment: 'This is exactly what I was looking for. Professional, clean, and easy to customize.', date: '3 weeks ago' },
  { id: 'r5', author: 'Rachel N.', avatar: 'RN', rating: 5, comment: 'Landed my dream job using this resume template. The AI suggestions were spot on!', date: '1 month ago' },
  { id: 'r6', author: 'Chris B.', avatar: 'CB', rating: 4, comment: 'Solid template. Used it for 3 clients already. Each time it looked polished and unique.', date: '1 month ago' },
];

export const MARKETPLACE_TEMPLATES: MarketplaceTemplate[] = [
  {
    id: 'mkt-001',
    title: 'Executive Resume Pro',
    description: 'A premium ATS-optimized resume template designed for senior executives and C-suite professionals. Includes multiple page layouts.',
    category: 'career',
    type: 'resume',
    price: 19,
    seller: SELLERS[0],
    rating: 4.9,
    reviewCount: 247,
    downloadCount: 3840,
    previewColor: 'from-indigo-600 to-purple-600',
    tags: ['resume', 'executive', 'ATS-friendly', 'professional'],
    featured: true,
    createdAt: '2024-10-15',
    reviews: [SAMPLE_REVIEWS[0], SAMPLE_REVIEWS[4]],
  },
  {
    id: 'mkt-002',
    title: 'SaaS Startup Business Plan',
    description: 'Comprehensive 40-page business plan template built for SaaS startups. Includes financial projections, market analysis, and investor pitch sections.',
    category: 'business',
    type: 'business-plan',
    price: 49,
    seller: SELLERS[2],
    rating: 5.0,
    reviewCount: 189,
    downloadCount: 2100,
    previewColor: 'from-violet-600 to-indigo-600',
    tags: ['business plan', 'SaaS', 'startup', 'investor'],
    featured: true,
    createdAt: '2024-09-20',
    reviews: [SAMPLE_REVIEWS[1], SAMPLE_REVIEWS[3]],
  },
  {
    id: 'mkt-003',
    title: 'Freelancer Invoice Suite',
    description: 'Beautiful invoice templates for freelancers and agencies. 5 design variations, automatic calculations, and client-ready formatting.',
    category: 'finance',
    type: 'invoice',
    price: 12,
    seller: SELLERS[4],
    rating: 4.8,
    reviewCount: 432,
    downloadCount: 8900,
    previewColor: 'from-amber-500 to-orange-600',
    tags: ['invoice', 'freelancer', 'finance', 'billing'],
    featured: true,
    createdAt: '2024-08-12',
    reviews: [SAMPLE_REVIEWS[2], SAMPLE_REVIEWS[5]],
  },
  {
    id: 'mkt-004',
    title: '90-Day Content Calendar',
    description: 'Plan 3 months of content across all platforms. Includes hooks library, hashtag strategy, and posting time optimization guide.',
    category: 'content',
    type: 'content-calendar',
    price: 27,
    seller: SELLERS[1],
    rating: 4.9,
    reviewCount: 156,
    downloadCount: 2890,
    previewColor: 'from-pink-500 to-rose-600',
    tags: ['content', 'social media', 'calendar', 'marketing'],
    featured: true,
    createdAt: '2024-11-01',
    reviews: [SAMPLE_REVIEWS[0], SAMPLE_REVIEWS[2]],
  },
  {
    id: 'mkt-005',
    title: 'Tech Industry Resume Pack',
    description: 'Specialized resume templates for software engineers, data scientists, and product managers. Includes GitHub portfolio integration tips.',
    category: 'career',
    type: 'resume',
    price: 24,
    seller: SELLERS[5],
    rating: 4.8,
    reviewCount: 98,
    downloadCount: 1560,
    previewColor: 'from-cyan-500 to-blue-600',
    tags: ['resume', 'tech', 'engineering', 'developer'],
    featured: false,
    createdAt: '2024-10-28',
    reviews: [SAMPLE_REVIEWS[4], SAMPLE_REVIEWS[1]],
  },
  {
    id: 'mkt-006',
    title: 'Agency Proposal Template',
    description: 'Win more clients with this conversion-optimized proposal template used by top agencies. Includes pricing tables and testimonial sections.',
    category: 'business',
    type: 'proposal',
    price: 35,
    seller: SELLERS[6],
    rating: 4.9,
    reviewCount: 74,
    downloadCount: 1240,
    previewColor: 'from-emerald-500 to-teal-600',
    tags: ['proposal', 'agency', 'client', 'pitch'],
    featured: false,
    createdAt: '2024-11-10',
    reviews: [SAMPLE_REVIEWS[3], SAMPLE_REVIEWS[5]],
  },
  {
    id: 'mkt-007',
    title: 'Persuasive Cover Letter Bundle',
    description: '10 proven cover letter templates for different industries and experience levels. Psychology-backed persuasion principles built in.',
    category: 'career',
    type: 'cover-letter',
    price: 15,
    seller: SELLERS[3],
    rating: 4.7,
    reviewCount: 211,
    downloadCount: 4320,
    previewColor: 'from-blue-500 to-indigo-600',
    tags: ['cover letter', 'career', 'job search', 'hiring'],
    featured: false,
    createdAt: '2024-09-05',
    reviews: [SAMPLE_REVIEWS[0], SAMPLE_REVIEWS[4]],
  },
  {
    id: 'mkt-008',
    title: 'Annual Budget Masterplan',
    description: 'Enterprise-grade budget planning template with automated formulas, variance analysis, and department breakdowns.',
    category: 'finance',
    type: 'budget-plan',
    price: 39,
    seller: SELLERS[7],
    rating: 4.6,
    reviewCount: 63,
    downloadCount: 890,
    previewColor: 'from-green-500 to-emerald-600',
    tags: ['budget', 'finance', 'planning', 'enterprise'],
    featured: false,
    createdAt: '2024-08-22',
    reviews: [SAMPLE_REVIEWS[2], SAMPLE_REVIEWS[5]],
  },
  {
    id: 'mkt-009',
    title: 'Instagram Growth Kit',
    description: 'Complete social media kit for Instagram influencers and brands. Includes content calendar, caption templates, hashtag research system.',
    category: 'content',
    type: 'social-media-kit',
    price: 22,
    seller: SELLERS[4],
    rating: 4.9,
    reviewCount: 178,
    downloadCount: 5670,
    previewColor: 'from-fuchsia-500 to-pink-600',
    tags: ['instagram', 'social media', 'influencer', 'content'],
    featured: true,
    createdAt: '2024-10-18',
    reviews: [SAMPLE_REVIEWS[1], SAMPLE_REVIEWS[3]],
  },
  {
    id: 'mkt-010',
    title: 'Press Release Master Template',
    description: 'Get media coverage with this journalist-approved press release template. Includes headline formulas, media list guidance, and followup email templates.',
    category: 'content',
    type: 'press-release',
    price: 18,
    seller: SELLERS[0],
    rating: 4.8,
    reviewCount: 52,
    downloadCount: 1120,
    previewColor: 'from-slate-600 to-gray-700',
    tags: ['press release', 'PR', 'media', 'publicity'],
    featured: false,
    createdAt: '2024-11-20',
    reviews: [SAMPLE_REVIEWS[0], SAMPLE_REVIEWS[2]],
  },
  {
    id: 'mkt-011',
    title: 'Restaurant Business Plan',
    description: 'Tailored for food & beverage entrepreneurs. Includes menu structure, cost of goods analysis, location analysis, and staff planning.',
    category: 'business',
    type: 'business-plan',
    price: 44,
    seller: SELLERS[2],
    rating: 4.8,
    reviewCount: 87,
    downloadCount: 1980,
    previewColor: 'from-orange-500 to-red-600',
    tags: ['restaurant', 'food', 'hospitality', 'business plan'],
    featured: false,
    createdAt: '2024-09-15',
    reviews: [SAMPLE_REVIEWS[4], SAMPLE_REVIEWS[5]],
  },
  {
    id: 'mkt-012',
    title: 'Creative Portfolio Resume',
    description: 'Stand out with this visually stunning resume template for designers, creatives, and marketing professionals.',
    category: 'career',
    type: 'resume',
    price: 21,
    seller: SELLERS[6],
    rating: 4.9,
    reviewCount: 143,
    downloadCount: 2780,
    previewColor: 'from-violet-500 to-pink-600',
    tags: ['resume', 'creative', 'designer', 'portfolio'],
    featured: false,
    createdAt: '2024-10-05',
    reviews: [SAMPLE_REVIEWS[3], SAMPLE_REVIEWS[1]],
  },
  {
    id: 'mkt-013',
    title: 'Consulting Proposal Pro',
    description: 'Close high-ticket consulting deals faster. Includes risk matrix, ROI calculator section, and elegant executive summary layout.',
    category: 'business',
    type: 'proposal',
    price: 55,
    seller: SELLERS[1],
    rating: 4.9,
    reviewCount: 61,
    downloadCount: 820,
    previewColor: 'from-teal-600 to-cyan-600',
    tags: ['consulting', 'proposal', 'B2B', 'high-ticket'],
    featured: false,
    createdAt: '2024-11-12',
    reviews: [SAMPLE_REVIEWS[0], SAMPLE_REVIEWS[5]],
  },
  {
    id: 'mkt-014',
    title: 'YouTube Content Strategy Kit',
    description: 'Everything a YouTube creator needs: content calendar, video script templates, SEO optimization guide, and thumbnail brief template.',
    category: 'content',
    type: 'content-calendar',
    price: 29,
    seller: SELLERS[3],
    rating: 4.7,
    reviewCount: 95,
    downloadCount: 1840,
    previewColor: 'from-red-500 to-rose-600',
    tags: ['youtube', 'video', 'creator', 'content'],
    featured: false,
    createdAt: '2024-09-28',
    reviews: [SAMPLE_REVIEWS[2], SAMPLE_REVIEWS[4]],
  },
  {
    id: 'mkt-015',
    title: 'Personal Finance Budget Template',
    description: 'Take control of your finances with this beautifully designed personal budget template. Tracks income, expenses, savings goals, and debt payoff.',
    category: 'finance',
    type: 'budget-plan',
    price: 9,
    seller: SELLERS[7],
    rating: 4.8,
    reviewCount: 320,
    downloadCount: 12400,
    previewColor: 'from-lime-500 to-green-600',
    tags: ['personal finance', 'budget', 'savings', 'debt'],
    featured: false,
    createdAt: '2024-08-01',
    reviews: [SAMPLE_REVIEWS[3], SAMPLE_REVIEWS[5]],
  },
  {
    id: 'mkt-016',
    title: 'SaaS Marketing Proposal',
    description: 'Design your SaaS growth strategy with this data-driven marketing proposal template. Includes funnel mapping and channel attribution models.',
    category: 'business',
    type: 'proposal',
    price: 42,
    seller: SELLERS[5],
    rating: 4.8,
    reviewCount: 48,
    downloadCount: 760,
    previewColor: 'from-indigo-500 to-blue-600',
    tags: ['SaaS', 'marketing', 'growth', 'proposal'],
    featured: false,
    createdAt: '2024-11-08',
    reviews: [SAMPLE_REVIEWS[1], SAMPLE_REVIEWS[0]],
  },
  {
    id: 'mkt-017',
    title: 'Healthcare Professional Resume',
    description: 'Specifically designed for doctors, nurses, and healthcare administrators. HIPAA-aware language, clinical skills section, and licensure fields.',
    category: 'career',
    type: 'resume',
    price: 17,
    seller: SELLERS[2],
    rating: 4.9,
    reviewCount: 88,
    downloadCount: 1540,
    previewColor: 'from-sky-500 to-blue-600',
    tags: ['healthcare', 'medical', 'nurse', 'doctor'],
    featured: false,
    createdAt: '2024-10-22',
    reviews: [SAMPLE_REVIEWS[4], SAMPLE_REVIEWS[2]],
  },
  {
    id: 'mkt-018',
    title: 'E-Commerce Business Plan',
    description: 'Complete business plan for online store launches. Covers Shopify setup, supplier strategy, marketing budget, and profitability timeline.',
    category: 'business',
    type: 'business-plan',
    price: 37,
    seller: SELLERS[0],
    rating: 4.7,
    reviewCount: 112,
    downloadCount: 2340,
    previewColor: 'from-purple-500 to-violet-600',
    tags: ['e-commerce', 'shopify', 'online store', 'retail'],
    featured: false,
    createdAt: '2024-09-10',
    reviews: [SAMPLE_REVIEWS[3], SAMPLE_REVIEWS[1]],
  },
  {
    id: 'mkt-019',
    title: 'LinkedIn Content Calendar',
    description: 'Dominate LinkedIn with 30 days of strategic content. Includes thought leadership post templates, engagement hooks, and connection request scripts.',
    category: 'content',
    type: 'content-calendar',
    price: 19,
    seller: SELLERS[6],
    rating: 4.9,
    reviewCount: 203,
    downloadCount: 4560,
    previewColor: 'from-blue-600 to-indigo-700',
    tags: ['linkedin', 'B2B', 'thought leadership', 'content'],
    featured: true,
    createdAt: '2024-11-05',
    reviews: [SAMPLE_REVIEWS[0], SAMPLE_REVIEWS[5]],
  },
  {
    id: 'mkt-020',
    title: 'Contractor Invoice Template',
    description: 'Professional invoice template for independent contractors. Auto-calculates taxes, includes milestone tracking, and retainer agreement sections.',
    category: 'finance',
    type: 'invoice',
    price: 11,
    seller: SELLERS[4],
    rating: 4.6,
    reviewCount: 198,
    downloadCount: 6780,
    previewColor: 'from-yellow-500 to-amber-600',
    tags: ['contractor', 'invoice', 'B2B', 'tax'],
    featured: false,
    createdAt: '2024-08-30',
    reviews: [SAMPLE_REVIEWS[2], SAMPLE_REVIEWS[4]],
  },
  // More templates for richer marketplace
  {
    id: 'mkt-021',
    title: 'Non-Profit Grant Proposal',
    description: 'Structured around grant committee expectations. Includes impact metrics framework, budget justification, and evaluation plan sections.',
    category: 'business',
    type: 'proposal',
    price: 29,
    seller: SELLERS[3],
    rating: 4.8,
    reviewCount: 45,
    downloadCount: 890,
    previewColor: 'from-emerald-600 to-green-700',
    tags: ['non-profit', 'grant', 'proposal', 'NGO'],
    featured: false,
    createdAt: '2024-10-01',
    reviews: [SAMPLE_REVIEWS[1], SAMPLE_REVIEWS[3]],
  },
  {
    id: 'mkt-022',
    title: 'Real Estate Cover Letter',
    description: 'Stand out in competitive real estate markets with personalized offer letters and housing application cover letters.',
    category: 'career',
    type: 'cover-letter',
    price: 14,
    seller: SELLERS[1],
    rating: 4.7,
    reviewCount: 67,
    downloadCount: 1230,
    previewColor: 'from-stone-600 to-zinc-700',
    tags: ['real estate', 'cover letter', 'property', 'rental'],
    featured: false,
    createdAt: '2024-11-18',
    reviews: [SAMPLE_REVIEWS[0], SAMPLE_REVIEWS[5]],
  },
  {
    id: 'mkt-023',
    title: 'TikTok Growth Strategy Kit',
    description: 'Viral-focused content kit for TikTok creators. Includes hook formulas, trending audio strategy, content batching system.',
    category: 'content',
    type: 'social-media-kit',
    price: 24,
    seller: SELLERS[4],
    rating: 4.9,
    reviewCount: 134,
    downloadCount: 3210,
    previewColor: 'from-pink-600 to-purple-700',
    tags: ['tiktok', 'viral', 'creator', 'short-form'],
    featured: false,
    createdAt: '2024-10-12',
    reviews: [SAMPLE_REVIEWS[2], SAMPLE_REVIEWS[4]],
  },
  {
    id: 'mkt-024',
    title: 'Startup Financial Model',
    description: '5-year financial projection model for early-stage startups. Includes burn rate calculator, runway tracker, and revenue assumptions.',
    category: 'finance',
    type: 'budget-plan',
    price: 59,
    seller: SELLERS[2],
    rating: 5.0,
    reviewCount: 39,
    downloadCount: 620,
    previewColor: 'from-cyan-600 to-teal-700',
    tags: ['startup', 'financial model', 'projections', 'VC'],
    featured: false,
    createdAt: '2024-09-25',
    reviews: [SAMPLE_REVIEWS[1], SAMPLE_REVIEWS[0]],
  },
  {
    id: 'mkt-025',
    title: 'HR Meeting Agenda Bundle',
    description: '12 ready-to-use meeting agenda templates for HR professionals. Covers hiring, performance reviews, onboarding, and culture meetings.',
    category: 'business',
    type: 'meeting-agenda',
    price: 16,
    seller: SELLERS[7],
    rating: 4.7,
    reviewCount: 82,
    downloadCount: 1890,
    previewColor: 'from-rose-500 to-red-600',
    tags: ['HR', 'meeting', 'agenda', 'management'],
    featured: false,
    createdAt: '2024-10-28',
    reviews: [SAMPLE_REVIEWS[3], SAMPLE_REVIEWS[5]],
  },
  {
    id: 'mkt-026',
    title: 'Product Launch Press Kit',
    description: 'Everything you need for a successful product launch. Press release template, product description, FAQ, media assets guide.',
    category: 'content',
    type: 'press-release',
    price: 32,
    seller: SELLERS[0],
    rating: 4.8,
    reviewCount: 58,
    downloadCount: 980,
    previewColor: 'from-amber-600 to-yellow-600',
    tags: ['launch', 'PR', 'press kit', 'product'],
    featured: false,
    createdAt: '2024-11-15',
    reviews: [SAMPLE_REVIEWS[4], SAMPLE_REVIEWS[2]],
  },
  {
    id: 'mkt-027',
    title: 'MBA Graduate Resume',
    description: 'Optimized for newly graduated MBA students entering consulting, finance, or strategy roles. Includes leadership and case study sections.',
    category: 'career',
    type: 'resume',
    price: 22,
    seller: SELLERS[5],
    rating: 4.8,
    reviewCount: 156,
    downloadCount: 2980,
    previewColor: 'from-indigo-700 to-blue-800',
    tags: ['MBA', 'graduate', 'consulting', 'finance'],
    featured: false,
    createdAt: '2024-09-08',
    reviews: [SAMPLE_REVIEWS[0], SAMPLE_REVIEWS[3]],
  },
  {
    id: 'mkt-028',
    title: 'Event Sponsorship Proposal',
    description: 'Professional sponsorship proposal template for events, podcasts, and content creators. Includes tier packages and ROI justification.',
    category: 'business',
    type: 'proposal',
    price: 28,
    seller: SELLERS[6],
    rating: 4.7,
    reviewCount: 41,
    downloadCount: 760,
    previewColor: 'from-purple-600 to-fuchsia-700',
    tags: ['sponsorship', 'events', 'proposal', 'brand deal'],
    featured: false,
    createdAt: '2024-11-22',
    reviews: [SAMPLE_REVIEWS[5], SAMPLE_REVIEWS[1]],
  },
  {
    id: 'mkt-029',
    title: 'Podcast Content Planning Kit',
    description: 'Plan an entire podcast season with episode arc planning, guest outreach templates, and show notes structure.',
    category: 'content',
    type: 'content-calendar',
    price: 23,
    seller: SELLERS[3],
    rating: 4.8,
    reviewCount: 77,
    downloadCount: 1440,
    previewColor: 'from-violet-600 to-purple-700',
    tags: ['podcast', 'audio', 'content', 'creator'],
    featured: false,
    createdAt: '2024-10-20',
    reviews: [SAMPLE_REVIEWS[2], SAMPLE_REVIEWS[0]],
  },
  {
    id: 'mkt-030',
    title: 'Construction Business Invoice',
    description: 'Specialized invoice template for contractors and construction businesses. Includes materials, labor, permits, and progress payment schedules.',
    category: 'finance',
    type: 'invoice',
    price: 14,
    seller: SELLERS[7],
    rating: 4.6,
    reviewCount: 93,
    downloadCount: 2100,
    previewColor: 'from-orange-600 to-amber-700',
    tags: ['construction', 'contractor', 'invoice', 'materials'],
    featured: false,
    createdAt: '2024-08-18',
    reviews: [SAMPLE_REVIEWS[4], SAMPLE_REVIEWS[3]],
  },
];

// ── Helper functions ───────────────────────────────────────────────────────

export function getFeaturedTemplates(): MarketplaceTemplate[] {
  return MARKETPLACE_TEMPLATES.filter(t => t.featured);
}

export function getTemplateById(id: string): MarketplaceTemplate | undefined {
  return MARKETPLACE_TEMPLATES.find(t => t.id === id);
}

export function getTemplatesByCategory(category: string): MarketplaceTemplate[] {
  if (category === 'all') return MARKETPLACE_TEMPLATES;
  return MARKETPLACE_TEMPLATES.filter(t => t.category === category);
}

export function searchTemplates(query: string, category?: string, maxPrice?: number, minRating?: number): MarketplaceTemplate[] {
  let results = MARKETPLACE_TEMPLATES;
  if (category && category !== 'all') {
    results = results.filter(t => t.category === category);
  }
  if (query) {
    const q = query.toLowerCase();
    results = results.filter(t =>
      t.title.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some(tag => tag.toLowerCase().includes(q))
    );
  }
  if (maxPrice !== undefined) {
    results = results.filter(t => t.price <= maxPrice);
  }
  if (minRating !== undefined) {
    results = results.filter(t => t.rating >= minRating);
  }
  return results;
}

export function getRelatedTemplates(template: MarketplaceTemplate, limit = 4): MarketplaceTemplate[] {
  return MARKETPLACE_TEMPLATES
    .filter(t => t.id !== template.id && (t.category === template.category || t.type === template.type))
    .slice(0, limit);
}
